import { newId } from './id'
import type { Division, LeagueState, PoolWrestler } from './types'

export const PROMOTIONS = ['WWE', 'NXT', 'AEW', 'TNA', 'Other'] as const

type Seed = [name: string, promotion: string, division: Division]

/**
 * Starting pool, seeded from the WWE, NXT, AEW, and TNA rosters. It is a snapshot rather than a live
 * feed, so names can be added or removed on the Roster Pool page as talent moves around.
 */
const SEED: Seed[] = [
  ['Cody Rhodes', 'WWE', 'men'],
  ['Roman Reigns', 'WWE', 'men'],
  ['Seth Rollins', 'WWE', 'men'],
  ['CM Punk', 'WWE', 'men'],
  ['Drew McIntyre', 'WWE', 'men'],
  ['Gunther', 'WWE', 'men'],
  ['Randy Orton', 'WWE', 'men'],
  ['LA Knight', 'WWE', 'men'],
  ['Jey Uso', 'WWE', 'men'],
  ['Jimmy Uso', 'WWE', 'men'],
  ['Solo Sikoa', 'WWE', 'men'],
  ['Bron Breakker', 'WWE', 'men'],
  ['Sami Zayn', 'WWE', 'men'],
  ['Kevin Owens', 'WWE', 'men'],
  ['Damian Priest', 'WWE', 'men'],
  ['Finn Balor', 'WWE', 'men'],
  ['JD McDonagh', 'WWE', 'men'],
  ['Dominik Mysterio', 'WWE', 'men'],
  ['Rey Mysterio', 'WWE', 'men'],
  ['AJ Styles', 'WWE', 'men'],
  ['Karrion Kross', 'WWE', 'men'],
  ['Shinsuke Nakamura', 'WWE', 'men'],
  ['Jacob Fatu', 'WWE', 'men'],
  ['Braun Strowman', 'WWE', 'men'],
  ['Sheamus', 'WWE', 'men'],
  ['Ludwig Kaiser', 'WWE', 'men'],
  ['Chad Gable', 'WWE', 'men'],
  ['Otis', 'WWE', 'men'],
  ['Andrade', 'WWE', 'men'],
  ['Carmelo Hayes', 'WWE', 'men'],
  ['Austin Theory', 'WWE', 'men'],
  ['Grayson Waller', 'WWE', 'men'],
  ['Apollo Crews', 'WWE', 'men'],
  ['Bobby Lashley', 'WWE', 'men'],
  ['Angelo Dawkins', 'WWE', 'men'],
  ['Montez Ford', 'WWE', 'men'],
  ['Bianca Belair', 'WWE', 'women'],
  ['Rhea Ripley', 'WWE', 'women'],
  ['Liv Morgan', 'WWE', 'women'],
  ['Becky Lynch', 'WWE', 'women'],
  ['Bayley', 'WWE', 'women'],
  ['Iyo Sky', 'WWE', 'women'],
  ['Asuka', 'WWE', 'women'],
  ['Kairi Sane', 'WWE', 'women'],
  ['Naomi', 'WWE', 'women'],
  ['Jade Cargill', 'WWE', 'women'],
  ['Tiffany Stratton', 'WWE', 'women'],
  ['Nia Jax', 'WWE', 'women'],
  ['Chelsea Green', 'WWE', 'women'],
  ['Piper Niven', 'WWE', 'women'],
  ['Alexa Bliss', 'WWE', 'women'],
  ['Raquel Rodriguez', 'WWE', 'women'],
  ['Zelina Vega', 'WWE', 'women'],
  ['Candice LeRae', 'WWE', 'women'],
  ['Indi Hartwell', 'WWE', 'women'],
  ['Lyra Valkyria', 'WWE', 'women'],

  ['Oba Femi', 'NXT', 'men'],
  ['Trick Williams', 'NXT', 'men'],
  ['Ethan Page', 'NXT', 'men'],
  ['Je’Von Evans', 'NXT', 'men'],
  ['Wes Lee', 'NXT', 'men'],
  ['Tony D’Angelo', 'NXT', 'men'],
  ['Channing Lorenzo', 'NXT', 'men'],
  ['Joe Hendry', 'NXT', 'men'],
  ['Josh Briggs', 'NXT', 'men'],
  ['Brooks Jensen', 'NXT', 'men'],
  ['Axiom', 'NXT', 'men'],
  ['Nathan Frazer', 'NXT', 'men'],
  ['Lexis King', 'NXT', 'men'],
  ['Shawn Spears', 'NXT', 'men'],
  ['Eddy Thorpe', 'NXT', 'men'],
  ['Ridge Holland', 'NXT', 'men'],
  ['Roxanne Perez', 'NXT', 'women'],
  ['Giulia', 'NXT', 'women'],
  ['Stephanie Vaquer', 'NXT', 'women'],
  ['Cora Jade', 'NXT', 'women'],
  ['Jaida Parker', 'NXT', 'women'],
  ['Fallon Henley', 'NXT', 'women'],
  ['Jacy Jayne', 'NXT', 'women'],
  ['Thea Hail', 'NXT', 'women'],
  ['Kelani Jordan', 'NXT', 'women'],
  ['Sol Ruca', 'NXT', 'women'],
  ['Tatum Paxley', 'NXT', 'women'],
  ['Wren Sinclair', 'NXT', 'women'],

  ['Jon Moxley', 'AEW', 'men'],
  ['Swerve Strickland', 'AEW', 'men'],
  ['Will Ospreay', 'AEW', 'men'],
  ['Kenny Omega', 'AEW', 'men'],
  ['Bryan Danielson', 'AEW', 'men'],
  ['MJF', 'AEW', 'men'],
  ['Adam Copeland', 'AEW', 'men'],
  ['Christian Cage', 'AEW', 'men'],
  ['Orange Cassidy', 'AEW', 'men'],
  ['Darby Allin', 'AEW', 'men'],
  ['Hangman Adam Page', 'AEW', 'men'],
  ['Jay White', 'AEW', 'men'],
  ['Matthew Jackson', 'AEW', 'men'],
  ['Nicholas Jackson', 'AEW', 'men'],
  ['Claudio Castagnoli', 'AEW', 'men'],
  ['Wheeler Yuta', 'AEW', 'men'],
  ['PAC', 'AEW', 'men'],
  ['Ricochet', 'AEW', 'men'],
  ['Konosuke Takeshita', 'AEW', 'men'],
  ['Powerhouse Hobbs', 'AEW', 'men'],
  ['Ricky Starks', 'AEW', 'men'],
  ['Samoa Joe', 'AEW', 'men'],
  ['Hook', 'AEW', 'men'],
  ['Kyle Fletcher', 'AEW', 'men'],
  ['Mark Briscoe', 'AEW', 'men'],
  ['Daniel Garcia', 'AEW', 'men'],
  ['Rey Fenix', 'AEW', 'men'],
  ['Penta El Zero Miedo', 'AEW', 'men'],
  ['Toni Storm', 'AEW', 'women'],
  ['Mariah May', 'AEW', 'women'],
  ['Mercedes Mone', 'AEW', 'women'],
  ['Britt Baker', 'AEW', 'women'],
  ['Jamie Hayter', 'AEW', 'women'],
  ['Willow Nightingale', 'AEW', 'women'],
  ['Kris Statlander', 'AEW', 'women'],
  ['Thunder Rosa', 'AEW', 'women'],
  ['Hikaru Shida', 'AEW', 'women'],
  ['Serena Deeb', 'AEW', 'women'],
  ['Julia Hart', 'AEW', 'women'],
  ['Skye Blue', 'AEW', 'women'],
  ['Anna Jay', 'AEW', 'women'],
  ['Riho', 'AEW', 'women'],

  ['Moose', 'TNA', 'men'],
  ['Nic Nemeth', 'TNA', 'men'],
  ['Josh Alexander', 'TNA', 'men'],
  ['Eddie Edwards', 'TNA', 'men'],
  ['Mike Bailey', 'TNA', 'men'],
  ['Frankie Kazarian', 'TNA', 'men'],
  ['Steve Maclin', 'TNA', 'men'],
  ['Mustafa Ali', 'TNA', 'men'],
  ['Matt Hardy', 'TNA', 'men'],
  ['Jeff Hardy', 'TNA', 'men'],
  ['Ace Austin', 'TNA', 'men'],
  ['Chris Bey', 'TNA', 'men'],
  ['Leon Slater', 'TNA', 'men'],
  ['Laredo Kid', 'TNA', 'men'],
  ['Rich Swann', 'TNA', 'men'],
  ['Trey Miguel', 'TNA', 'men'],
  ['Jordynne Grace', 'TNA', 'women'],
  ['Masha Slamovich', 'TNA', 'women'],
  ['Rosemary', 'TNA', 'women'],
  ['Tasha Steelz', 'TNA', 'women'],
  ['Alisha Edwards', 'TNA', 'women'],
  ['Xia Brookside', 'TNA', 'women'],
  ['Ash By Elegance', 'TNA', 'women'],
  ['Dani Luna', 'TNA', 'women'],
  ['Spitfire', 'TNA', 'women'],
]

export function seedPool(): PoolWrestler[] {
  return SEED.map(([name, promotion, division]) => ({ id: newId(), name, promotion, division }))
}

/** Promotion first, then men before women, then alphabetical. */
export function sortPool(pool: PoolWrestler[]): PoolWrestler[] {
  return [...pool].sort(
    (a, b) =>
      a.promotion.localeCompare(b.promotion) ||
      (a.division === b.division ? 0 : a.division === 'men' ? -1 : 1) ||
      a.name.localeCompare(b.name),
  )
}

export function poolPromotions(state: LeagueState): string[] {
  return [...new Set(state.pool.map((p) => p.promotion))].sort((a, b) => a.localeCompare(b))
}
